Repository LastPracticant/ya-practicum-m2, pull requests merged in 2021-02, with the labels that each got.

#22 LP-6 Настройка ESLint, автоформатирования, LP-7 роутинг + зашблоны страниц
  .eslintignore
  .eslintrc
  client/App.tsx
  client/core/Navigation/Navigation.tsx
  client/core/Navigation/index.ts
  client/core/index.ts
  client/index.tsx
  client/pages/ErrorPage/ErrorPage.tsx
  client/pages/ErrorPage/ErrorPage.types.ts
  client/pages/ErrorPage/index.ts
  client/pages/Forum/Forum.tsx
  client/pages/Forum/index.ts
  client/pages/Game/Game.tsx
  client/pages/Game/index.ts
  client/pages/Home/Home.tsx
  client/pages/Home/index.ts
  client/pages/Leaderboard/Leaderboard.tsx
  client/pages/Leaderboard/index.ts
  client/pages/Profile/Profile.tsx
  client/pages/Profile/index.ts
  client/pages/Signin/Signin.tsx
  client/pages/Signin/index.ts
  client/pages/Signup/Signup.tsx
  client/pages/Signup/index.ts
  client/pages/index.ts
  client/routing/Routing.config.ts
  client/routing/Routing.tsx
  client/routing/index.ts
  client/shared/types/components.types.ts
  client/shared/types/index.ts
  package-lock.json
  package.json
  tsconfig.eslint.json
  tsconfig.json
  webpack.config.js
Labels: infrastructure

#23 LP-14: Обработка ошибок внутри «детей» React-компонентов.
  .eslintrc
  client/App.tsx
  client/core/components/ErrorBoundary/ErrorBoundary.tsx
  client/core/components/ErrorBoundary/index.ts
  client/core/components/Navigation/Navigation.tsx
  client/core/components/Navigation/index.ts
  client/core/components/index.ts
  client/core/index.ts
Labels: frontend

#24 LP-5: Сервис должен быть развернут на Heroku
  .dockerignore
  Dockerfile
  README.md
  package-lock.json
  package.json
  server/start.js
  webpack.config.js
Labels: infrastructure

#26 LP-11: подключение АПИ регистрации и авторизации, LP-12
  .eslintrc
  README.md
  client/App.tsx
  client/core/api/api.consts.ts
  client/core/api/api.ts
  client/core/api/auth.api.ts
  client/core/api/base.api.ts
  client/core/api/index.ts
  client/core/api/profile.api.ts
  client/core/components/Navigation/Navigation.tsx
  client/pages/ErrorPage/ErrorPage.types.ts
  client/pages/Forum/Forum.tsx
  client/pages/Game/Game.tsx
  client/pages/Home/Home.tsx
  client/pages/Leaderboard/Leaderboard.tsx
  client/pages/Profile/Profile.tsx
  client/pages/Signin/Signin.tsx
  client/pages/Signin/components/SignupForm/SigninForm.config.ts
  client/pages/Signin/components/SignupForm/SigninForm.tsx
  client/pages/Signin/components/SignupForm/index.ts
  client/pages/Signin/components/index.ts
  client/pages/Signup/Signup.tsx
  client/pages/Signup/components/SignupForm/SignupForm.config.ts
  client/pages/Signup/components/SignupForm/SignupForm.tsx
  client/pages/Signup/components/SignupForm/index.ts
  client/pages/Signup/components/index.ts
  client/shared/components/InputControl/InputControl.tsx
  client/shared/components/InputControl/index.ts
  client/shared/components/index.ts
  client/shared/consts/form.consts.ts
  client/shared/consts/index.ts
  package-lock.json
  package.json
  tsconfig.json
  webpack.config.js
Labels: backend, frontend, infrastructure

#21 LP-9 Добавлены компоненты, и добавлена theme проекта (LP-9, LP-10), также сверстана страница лидербортда LP-16
  .editorconfig
  .stylelintrc.json
  client/App.css
  client/App.tsx
  client/pages/Home/Home.tsx
  client/pages/Leaderboard/Leaderboard.tsx
  client/routing/Routing.config.ts
  client/routing/Routing.tsx
  client/shared/UiKit/UiKit.tsx
  client/shared/UiKit/components/Avatar/Avatar.demo.tsx
  client/shared/UiKit/components/Avatar/index.ts
  client/shared/UiKit/components/Button/Button.demo.tsx
  client/shared/UiKit/components/Button/index.ts
  client/shared/UiKit/components/Chip/Chip.demo.tsx
  client/shared/UiKit/components/Chip/index.ts
  client/shared/UiKit/components/Icon/Icon.demo.tsx
  client/shared/UiKit/components/Icon/index.ts
  client/shared/UiKit/components/List/List.demo.tsx
  client/shared/UiKit/components/List/index.ts
  client/shared/UiKit/components/index.ts
  client/shared/UiKit/index.ts
  client/shared/components/Avatar/Avatar.css
  client/shared/components/Avatar/Avatar.tsx
  client/shared/components/Avatar/index.ts
  client/shared/components/Button/Button.css
  client/shared/components/Button/Button.tsx
  client/shared/components/Button/index.ts
  client/shared/components/Chip/Chip.css
  client/shared/components/Chip/Chip.tsx
  client/shared/components/Chip/index.ts
  client/shared/components/Divider/Divider.css
  client/shared/components/Divider/Divider.tsx
  client/shared/components/Divider/index.ts
  client/shared/components/Icon/Icon.css
  client/shared/components/Icon/Icon.tsx
  client/shared/components/Icon/index.ts
  client/shared/components/InputControl/InputControl.css
  client/shared/components/InputControl/InputControl.tsx
  client/shared/components/Paper/Paper.css
  client/shared/components/Paper/Paper.tsx
  client/shared/components/Paper/index.ts
  client/shared/components/index.ts
  client/shared/styles/Theme/index.ts
  client/shared/styles/Theme/theme.css
  client/shared/styles/normalize.css
  package-lock.json
  package.json
  tsconfig.eslint.json
  webpack.config.js
  www/index.html
Labels: frontend

#32 LP-31 стабилизировал ветку после влития LP-9
  client/App.tsx
  client/core/components/Navigation/Navigation.css
  client/core/components/Navigation/Navigation.tsx
  client/pages/Home/Home.css
  client/pages/Home/Home.tsx
  client/pages/Home/home-bg.png
  client/pages/Leaderboard/Leaderboard.tsx
  client/routing/Routing.tsx
  client/shared/UiKit/UiKit.tsx
  client/shared/UiKit/components/Avatar/Avatar.demo.tsx
  client/shared/UiKit/components/Button/Button.demo.tsx
  client/shared/UiKit/components/Chip/Chip.demo.tsx
  client/shared/UiKit/components/Icon/Icon.demo.tsx
  client/shared/UiKit/components/List/List.demo.tsx
  client/shared/components/Avatar/Avatar.tsx
  client/shared/components/Chip/Chip.tsx
  client/shared/components/InputControl/InputControl.css
  client/shared/components/Paper/Paper.css
  client/shared/components/Paper/Paper.tsx
  client/shared/styles/Theme/index.ts
  client/shared/styles/Theme/theme.css
  client/shared/styles/theme.css
  package-lock.json
  package.json
  tsconfig.eslint.json
  webpack.config.js
Labels: infrastructure

#28 LP-27 Базовая механика игры на Canvas API
  .eslintrc
  client/core/components/GameCanvas/GameCanvas.config.ts
  client/core/components/GameCanvas/GameCanvas.hooks.tsx
  client/core/components/GameCanvas/GameCanvas.tsx
  client/core/components/GameCanvas/GamePainter.ts
  client/core/components/GameCanvas/ResourcesLoader.ts
  client/core/components/GameCanvas/img/bg4.png
  client/core/components/GameCanvas/img/bg5.png
  client/core/components/GameCanvas/img/hero.png
  client/core/components/GameCanvas/index.ts
  client/core/components/index.ts
  client/pages/Game/Game.tsx
  client/shared/types/images.d.ts
  client/shared/types/index.ts
  client/shared/types/utils.types.ts
  tsconfig.json
Labels: frontend

#57 LP-15: Страница форума
  client/core/components/GameCanvas/img/bg4.png
  client/core/components/GameCanvas/img/bg5.png
  client/core/components/Navigation/Navigation.tsx
  client/core/components/PageLayout/PageLayout.tsx
  client/pages/Forum/Forum.config.tsx
  client/pages/Forum/Forum.css
  client/pages/Forum/Forum.mock.ts
  client/pages/Forum/Forum.tsx
  client/pages/Forum/ForumBoard.tsx
  client/pages/Forum/ForumTopic.tsx
  client/pages/Forum/index.ts
  client/pages/Game/Game.tsx
  client/pages/Game/GameOver.tsx
  client/pages/Game/GameStart.tsx
  client/pages/Home/Home.tsx
  client/pages/Signup/components/SignupForm/SignupForm.tsx
  client/routing/Routing.config.ts
  client/routing/Routing.tsx
  client/shared/components/ButtonsToolbar/ButtonsToolbar.css
  client/shared/components/ButtonsToolbar/ButtonsToolbar.tsx
  client/shared/components/ButtonsToolbar/index.ts
  client/shared/components/Loader/Loader.tsx
  client/shared/components/NivelatorXY/NivelatorXY.tsx
  client/shared/components/Paper/Paper.css
  client/shared/components/Paper/Paper.tsx
  client/shared/components/index.ts
  client/shared/consts/text.ts
  client/shared/types/components.types.ts
  package-lock.json
  package.json
  server/start.js
  www/index.html
Labels: frontend, infrastructure

#58 LP-46: Добавить в игру текстуры: количество жизней, боеприпасы, взрывы
  client/core/components/GameCanvas/GameCanvas.config.ts
  client/core/components/GameCanvas/GameCanvas.hooks.tsx
  client/core/components/GameCanvas/GameCanvas.tsx
  client/core/components/GameCanvas/GamePainter.ts
  client/core/components/GameCanvas/ResourcesLoader.ts
  client/core/components/GameCanvas/img/enemies.png
  client/core/components/GameCanvas/img/explosion.png
  client/core/components/GameCanvas/img/idea.png
  client/core/components/GameCanvas/img/life.png
  client/pages/Game/Game.config.ts
  client/pages/Game/GameStart.tsx
  client/shared/components/Loader/Loader.tsx
Labels: frontend

#61 LP-41: Добавить в игру генерацию препятствий, LP-45, LP-60
  .eslintrc
  client/core/components/GameCanvas/GameCanvas.config.ts
  client/core/components/GameCanvas/GameCanvas.utils.ts
  client/core/components/GameCanvas/GamePainter.ts
  client/core/components/GameCanvas/img/enemies-v.png
  client/core/components/GameCanvas/img/enemies.png
  client/core/components/GameCanvas/img/explosion.png
  client/core/components/GameCanvas/img/hero.png
  client/pages/Profile/components/ProfileEdit/ProfileEdit.tsx
  client/shared/types/common.types.ts
  client/shared/types/index.ts
  client/shared/utils/common.utils.ts
  client/shared/utils/index.ts
Labels: frontend

#69 LP-68 привел стр. к виду стр. Форум
  client/pages/Leaderboard/Leaderboard.config.ts
  client/pages/Leaderboard/Leaderboard.mock.ts
  client/pages/Leaderboard/Leaderboard.tsx
  client/shared/consts/text.ts
Labels: frontend

#70 LP-64: Реализовать механику уменьшения жизней, расходования и восстановления снарядов
  .eslintrc
  README.md
  client/App.tsx
  client/core/components/GameCanvas/GameCanvas.config.ts
  client/core/components/GameCanvas/GameCanvas.hooks.tsx
  client/core/components/GameCanvas/GamePainter.ts
  client/core/components/PageLayout/PageLayout.css
  client/core/store/actions/game.actions.ts
  client/core/store/index.ts
  client/core/store/reducers/game.reducers.ts
  client/core/store/selectors/selectors.ts
  client/core/store/store.ts
  client/core/store/store.types.ts
  client/pages/Forum/Forum.config.tsx
  client/pages/Game/Game.css
  client/pages/Game/Game.tsx
  client/pages/Game/GameOver.tsx
  client/pages/Game/GameStart.tsx
  client/pages/Home/Home.tsx
  client/pages/Leaderboard/Leaderboard.config.ts
  client/pages/Profile/components/ProfileEdit/ProfileEdit.tsx
  client/pages/Profile/components/ProfileEditPassword/ProfileEditPassword.tsx
  client/pages/Profile/components/ProfileForm/ProfileForm.tsx
  client/pages/Signin/components/SigninForm/SigninForm.tsx
  client/pages/Signup/components/SignupForm/SignupForm.tsx
  client/routing/Routing.config.ts
  client/routing/Routing.tsx
  client/shared/components/AvatarUpload/AvatarUpload.tsx
  client/shared/consts/text.ts
  client/shared/types/utils.types.ts
  client/shared/utils/common.utils.ts
Labels: frontend

#67 LP-39: Добавить redux для профиля
  client/core/api/api.ts
  client/core/components/GameCanvas/ResourcesLoader.ts
  client/core/store/actions/index.ts
  client/core/store/actions/profile.actions.ts
  client/core/store/reducers/index.ts
  client/core/store/reducers/profile.reducers.ts
  client/core/store/selectors/index.ts
  client/core/store/selectors/loader.selectors.ts
  client/core/store/selectors/ptofile.selectors.ts
  client/core/store/store.ts
  client/core/store/store.types.ts
  client/pages/Home/Home.css
  client/pages/Home/Home.tsx
  client/pages/Profile/components/ProfileEdit/ProfileEdit.tsx
  client/pages/Profile/components/ProfileEditPassword/ProfileEditPassword.tsx
  client/pages/Profile/components/ProfileForm/ProfileForm.tsx
  client/pages/Signin/components/SigninForm/SigninForm.tsx
  client/pages/Signup/components/SignupForm/SignupForm.tsx
  client/pages/index.ts
  client/shared/components/AvatarUpload/AvatarUpload.tsx
Labels: frontend
